### ISSUE TITLE
Open dataset

### ISSUE THREAD

**Issue by JimmyChame** [guochengqian/TENet#2]
Hi, I read your paper and thought it was a good job. I want to know if your PixelShift dataset will be made public.  Thanks a lot.

**Comment by guochengqian** [comment]
@JimmyChame  Thanks. We will release our datasets soon, maybe in 15 days. Please star or watch the repo.

**Comment by laulampaul** [comment]
Hi，Could I ask a question？ where is the pixel-shift test dataset？Is it the valid dataset？Why don't you do the quantitative experiment on the pixel-shift test dataset ？
Thank you.

**Comment by guochengqian** [comment]
@laulampaul Thanks for leaving messages. Yes, as you see, there is no test dataset. Why? Because we conduct the quantitative experiment on the McM, Urban100, etc widely used datasets, just to show the effectiveness of our model architecture. It's not necessary to do quantitative exp on pixelshift200 dataset. That's fine if you want to, but you have to pre-train all the models(CARN, EDSR, DemosaicNet) on pixelshift200 training datasets at first for a fair comparison.

**Comment by laulampaul** [comment]
Excuse me, I want to ask some other questions. How many epochs are needed to train on the pixelshift dataset? Do you try to use the model trained on the pixelshift dataset to test on the McM, Urban100, etc test datasets?

**Comment by guochengqian** [comment]
> Hi，Could I ask a question？ where is the pixel-shift test dataset？Is it the valid dataset？Why don't you do the quantitative experiment on the pixel-shift test dataset ？
> Thank you.

Hi. @laulampaul The 10 images are the PixelShiftTest dataset. Sorry for the wrong information before.

**Comment by guochengqian** [comment]
> Excuse me, I want to ask some other questions. How many epochs are needed to train on the pixelshift dataset? Do you try to use the model trained on the pixelshift dataset to test on the McM, Urban100, etc test datasets?

1000,000 iterations are enough to have the same result as we published. Rember, not the epochs. 
For the second question, no. They are not the same data format. Comparison is not fair.

**Comment by zhaowei11594** [comment]
may you add a BaiduYun link？

**Comment by guochengqian** [comment]
BaiduYun is slow to use. I'm so sorry for the inconvenience.
