### ISSUE TITLE
how to convert rgb image to Bayer raw images (bayer pattern is rggb)

### ISSUE THREAD

**Issue by aligoglos** [guochengqian/TENet#5]
I want to test my images on your model but I don't know how to convert normal image to rggb.
Have you any script for that?

**Comment by guochengqian** [comment]
> I want to test my images on your model but I don't know how to convert normal image to rggb.
> Have you any script for that?

Hi, I may release codes for processing any image one month later. During these days, I'm too busy. Sorry.

**Comment by laulampaul** [comment]
I also want the code which converts RGB images to Bayer lr_raw images in your paper because it seems my code has something wrong to convert image in gt of TENet_sim_test to the input of TENet_sim_test.

**Comment by guochengqian** [comment]
To convert from RGB to Bayer Lr is simply composed of two steps. First, average pixel values to downsample, then index R, G, B values according to your bayer pattern to obtain Bayer images from RGB in the usual way. 

The codes of the above two steps are already contained in TorchTools. It's reasonable that you need an easy function to process them directly. In my new version code, I make code neat, but I haven't tested whether the code works or not. Since I don't fully work on this project any more, please give me some time to do it. Or maybe I can just add my code of processing RGB images here for convenience when I'm back to university in September.

**Comment by guochengqian** [comment]
I add a demo code to convert RGB to Low-Resolution Bayer Raw. I will close the issue.  If you have more help, please contact me.

**Comment by giardiello** [comment]
Hello, I would also like to convert linear 16bit images to Bayer Raw to test your code. How can I do it?

**Comment by guochengqian** [comment]
@giardiello 
I will not offer the code directly, however, I can give you some hints. You can revise the code I published in the home folder called rgb2raw.py.  But be careful,  rgb2raw.py is designed for 8bit images. Just change the code a little bit and convert your images to (0,1) according to the data type of your original images. Also, be careful of the bayer_pattern as well as the white balance.

**Comment by giardiello** [comment]
Thank you.
I will take a look.



⁣--  
Francesco Luigi Giardiello
Digital Workflow Supervisor 
Mob. UK +44 (0) 7932745460
Mob. IT +39 340 1505614 
Office US +1 (818) 533-9733 
Skype f.giardiello ​

**Comment by yemre-data** [comment]
def rgb2rb(im_rgb):
    H = im_rgb.shape[0]
    W = im_rgb.shape[1]
    im = np.zeros((im_rgb.shape[0], im_rgb.shape[1]))
    im[1:H:2, 1:W:2] = im_rgb[1:H:2, 1:W:2, 0]
    im[1:H:2, 0:W:2] = im_rgb[1:H:2, 0:W:2, 1]
    im[0:H:2, 1:W:2] = im_rgb[0:H:2, 1:W:2, 1]
    im[0:H:2, 0:W:2] = im_rgb[0:H:2, 0:W:2, 2]
    return np.uint8(im)


simple way to that
